spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: overcutf1web@gmail.com
    password: hezivclnvcjtnyvf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

