spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: overcutwebf1@gmail.com
    password: ixbtqhsujpkqyyzx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

