logging:
  level:
    org:
      hibernate:
        SQL: debug
spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    max-active: 4
    max-idle: 2
    max-wait: 10000
    remove-abandoned: true
    remove-abandoned-timeout: 60
    log-abandoned: true
    validation-query: SELECT 1

  spring:
    ai:
      spring:
        ai:
          ollama:
            enabled: true
            mistral:
              model: mistral-small-latest
              temperature: 0.6
      mistralai:
        api-key: T7R8rE9gSMV0rdDoH0iez5UrTFz6TzwA
        chat:
          options:
            model: mistral-small-latest
            temperature: 0.6
  devtools:
    restart:
      trigger-file: reload
    liveReload:
      enabled: false
  jackson:
    default-property-inclusion: NON_NULL
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
      show-sql: true
      format-sql: true
      use-sql-comments: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  main:
    allow-bean-definition-overriding: true

server:
  servlet:
    context-path: '@project.contextPath@'
project:
  jwt:
    signKey: WzROun12eUiDvko3UrJz2TWEWPMTh6DxyE8HWXIf4hETUrkM4IUGqqHq66PuVS1234567890
    expirationMinutes: 1440

llm:
  api:
    key: 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
  model: gpt-4
  openai:
    url: https://api.openai.com/v1