logging:
  level:
    org:
      hibernate:
        SQL: debug
spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    max-active: 4
    max-idle: 2
    max-wait: 10000
    remove-abandoned: true
    remove-abandoned-timeout: 60
    log-abandoned: true
    validation-query: SELECT 1



  ai:
    openai:
      api-key: ${OPENAI_API_KEY}  # Asegúrate de usar la variable de entorno correctamente
      model: gpt-4
      base-url: https://api.openai.com/v1/completions
      temperature: 0.7  # Ajusta la temperatura según lo que necesites
    mistralai:
      api-key: T7R8rE9gSMV0rdDoH0iez5UrTFz6TzwA
      chat:
        options:
          model: mistral-small-latest
          temperature: 0.6
  devtools:
    restart:
      trigger-file: reload
    liveReload:
      enabled: false
  jackson:
    default-property-inclusion: NON_NULL
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
      show-sql: true
      format-sql: true
      use-sql-comments: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  main:
    allow-bean-definition-overriding: true

server:
  servlet:
    context-path: '@project.contextPath@'
project:
  jwt:
    signKey: WzROun12eUiDvko3UrJz2TWEWPMTh6DxyE8HWXIf4hETUrkM4IUGqqHq66PuVS1234567890
    expirationMinutes: 1440



ergast:
  api:
    base-url: https://api.jolpi.ca/ergast/f1