CREATE TABLE IF NOT EXISTS CareerModeSave (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    exportCode CHAR(12) NOT NULL,
    payload MEDIUMBLOB NOT NULL,
    payloadSize INT NOT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_career_mode_save_export_code (exportCode)
);
