const getModuleState = state => state.statistics;

export const getDriverStandings = state => getModuleState(state).driverStandings;
export const getConstructorStandings = state => getModuleState(state).constructorStandings;
export const getDriverWins = state => getModuleState(state).driverWins;
export const getDriverPodiums = state => getModuleState(state).driverPodiums;
export const getDriverPoles = state => getModuleState(state).driverPoles;
export const getDriverGrandChelems = state => getModuleState(state).driverGrandChelems;
export const getDriverWinsByTeam = state => getModuleState(state).driverWinsByTeam;
export const getDriverPodiumsByTeam = state => getModuleState(state).driverPodiumsByTeam;
export const getDriverPolesByTeam = state => getModuleState(state).driverPolesByTeam;
export const getConstructors = state => getModuleState(state).constructors;
export const getChampionsByTitleCount = state => getModuleState(state).championsByTitleCount;
export const getChampionsChronologically = state => getModuleState(state).championsChronologically;
export const getChampionsByAge = state => getModuleState(state).championsByAge;
export const getConsecutiveTitles = state => getModuleState(state).consecutiveTitles;
export const getLongestGapBetweenTitles = state => getModuleState(state).longestGapBetweenTitles;
export const getGpCountBeforeTitle = state => getModuleState(state).gpCountBeforeTitle;
export const getChampionsByConstructorVariety = state => getModuleState(state).championsByConstructorVariety;
export const getDriverWinsChronologically = state => getModuleState(state).driverWinsChronologically;
export const getTeamWinsChronologically = state => getModuleState(state).teamWinsChronologically;
export const getYoungestDriversAtFirstWin = state => getModuleState(state).youngestWinDrivers;
export const getOldestDriversToWin = state => getModuleState(state).oldestWinDrivers;
export const getWinsOnBirthday = state => getModuleState(state).winsOnBirthday;
export const getLongestConsecutiveWinStreaks = state => getModuleState(state).longestConsecutiveWinStreaks;
export const getLongestSeasonStartWinStreaks = state => getModuleState(state).seasonStartWinStreaks;
export const getLastCareerWinPerDriver = state => getModuleState(state).lastCareerWins;
export const getBiggestGapBetweenWins = state => getModuleState(state).biggestWinGaps;
export const getGapBetweenFirstAndLastWin = state => getModuleState(state).firstLastWinGaps;
export const getMostWinsInSingleYear = state => getModuleState(state).mostWinsSingleYear;
export const getMostYearsWithWins = state => getModuleState(state).mostYearsWithWins;
export const getMostConsecutiveWinningYears = state => getModuleState(state).mostConsecutiveWinningYears;
export const getGpCountBeforeFirstWin = state => getModuleState(state).gpCountBeforeFirstWin;

